### ISSUE TITLE
Make the closet page call the endpoint

### ISSUE THREAD

**Issue by madelesi** [cooperemily02/WeathertoWear#25]

**Comment by madelesi** [comment]
Look into `proxy` for the react package.json 

(automatically forwards `fetch` requests to the backend)

**Comment by madelesi** [comment]
https://blog.miguelgrinberg.com/post/how-to-create-a-react--flask-project

**Comment by Leugimlra** [comment]
https://www.geeksforgeeks.org/how-to-fetch-data-from-an-api-in-reactjs/
