### ISSUE TITLE
Write the database access instructions

### ISSUE THREAD

**Issue by madelesi** [cooperemily02/WeathertoWear#26]

**Comment by laurencockey** [comment]
https://docs.google.com/document/d/1PDPrWlMYVdF4zKljbQG60ldvi-vUu5o4LNMbQYE_GHM/edit?usp=sharing

**Comment by laurencockey** [comment]
I have this for the database access instructions based on my understanding. Eugene noted that he didn't think it had to be too detailed, but if anything is incorrect feel free to edit.
